# Generated by Django 5.0.4 on 2024-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_email', models.EmailField(default='', max_length=254)),
                ('aluno_pass', models.CharField(default='', max_length=255)),
                ('aluno_idade', models.IntegerField(default=0)),
                ('aluno_dataCadastro', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_nickname', models.CharField(default='', max_length=100)),
                ('pessoa_nome', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firebase_id', models.CharField(default='', max_length=255)),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('user_level', models.IntegerField(default=0)),
                ('user_dataCadastro', models.DateTimeField(default='')),
            ],
        ),
    ]
