# Generated by Django 5.0.4 on 2024-04-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_PESSOA_USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest.pessoa')),
                ('user_firebase_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest.user')),
            ],
        ),
    ]
