# Generated by Django 5.0.4 on 2024-04-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_rename_fk_pessoa_user_user_pessoa_fk_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pessoa',
            name='FK_PESSOA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FK_PESSOA', to='api_rest.pessoa'),
        ),
        migrations.AlterField(
            model_name='user_pessoa',
            name='FK_USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FK_USER', to='api_rest.user'),
        ),
    ]
