# Generated by Django 5.0.4 on 2024-04-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_user_pessoa_fk_pessoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_ALUNO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_ALUNO', to='api_rest.aluno')),
                ('FK_PESSOA_ALUNO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_PESSOA_ALUNO', to='api_rest.pessoa')),
            ],
        ),
    ]
