# Generated by Django 5.0.4 on 2024-04-26 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_aluno_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aluno_pessoa',
            name='FK_ALUNO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FK_ALUNO', to='api_rest.aluno'),
        ),
        migrations.AlterField(
            model_name='aluno_pessoa',
            name='FK_PESSOA_ALUNO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FK_PESSOA_ALUNO', to='api_rest.pessoa'),
        ),
    ]
