# Generated by Django 5.0.4 on 2024-04-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_geeksmodel_alter_aluno_pessoa_fk_aluno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
