# Generated by Django 5.0.4 on 2024-04-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_delete_geeksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_pessoa',
            name='FK_PESSOA',
        ),
        migrations.RemoveField(
            model_name='user_pessoa',
            name='FK_USER',
        ),
        migrations.AddField(
            model_name='user',
            name='pessoa_nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pessoa_nome',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='Aluno_Pessoa',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='User_Pessoa',
        ),
    ]
