# Generated by Django 5.0.4 on 2024-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_remove_user_pessoa_fk_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='pessoa_nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pessoa_nome',
            field=models.CharField(default='', max_length=150),
        ),
    ]
