# Generated by Django 5.0.4 on 2024-04-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_aluno_pessoa_nickname_aluno_pessoa_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_email',
            new_name='aluno_id_login',
        ),
    ]
