# Generated by Django 5.0.4 on 2024-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_rename_aluno_email_aluno_aluno_id_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aluno_id_login',
            field=models.IntegerField(default=0),
        ),
    ]
