# Generated by Django 5.0.4 on 2024-05-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_alter_aluno_aluno_id_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='professor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='api_rest.user'),
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(default='', max_length=1000)),
                ('resposta1', models.CharField(default='', max_length=1000)),
                ('resposta2', models.CharField(default='', max_length=1000)),
                ('resposta3', models.CharField(default='', max_length=1000)),
                ('resposta4', models.CharField(default='', max_length=1000)),
                ('dataInicio', models.DateTimeField(default='')),
                ('dataFinal', models.DateTimeField(default='')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='api_rest.user')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api_rest.aluno')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api_rest.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(default='', max_length=150)),
                ('classification', models.CharField(default='', max_length=1)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='api_rest.user')),
            ],
        ),
        migrations.AddField(
            model_name='questionario',
            name='temas',
            field=models.ManyToManyField(related_name='questoes', to='api_rest.tema'),
        ),
    ]
